### ISSUE TITLE
Its not working with Jenkins 2.70 and DSL 1.60 versions

### ISSUE THREAD

**Issue by bibinwilson** [sheehan/job-dsl-rest-example#2]
I tried using Github pull request builder trigger.

<pre>
Exception in thread "main" javaposse.jobdsl.dsl.DslScriptException: (script, line 17) No signature of method: javaposse.jobdsl.dsl.helpers.triggers.TriggerContext.githubPullRequest() is applicable for argument types: (script$_run_closure1$_closure4$_closure8) values: [script$_run_closure1$_closure4$_closure8@20f5281c]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
<pre>

**Comment by sheehan** [comment]
This example doesn't support the [Dynamic DSL](https://github.com/jenkinsci/job-dsl-plugin/wiki/Dynamic-DSL). You can try this plugin for that feature: https://github.com/heremaps/gradle-jenkins-jobdsl-plugin

**Comment by bibinwilson** [comment]
Thanks @sheehan for the update...
